version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contrasena
      POSTGRES_DB: cesfam
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  login-service:
    build: ./login-service
    container_name: login-service
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: usuario
      DB_PASSWORD: contrasena
      DB_NAME: cesfam
      JWT_SECRET: supersecreto123
    ports:
      - "3000:3000"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    depends_on:
      - login-service
      - prescripciones-service
      - pacientes-service
      - reservas-service
      - medicamentos-service
    environment:
      JWT_SECRET: supersecreto123
      LOGIN_SERVICE_URL: http://login-service:3000
      PRESCRIPCION_SERVICE_URL: http://prescripciones-service:3002
      PACIENTES_SERVICE_URL: http://pacientes-service:3003
      RESERVAS_SERVICE_URL: http://reservas-service:3004
      MEDICAMENTOS_SERVICE_URL: http://medicamentos-service:3005
    ports:
      - "8080:8080"

  prescripciones-service:
    build:
      context: ./prescripciones-service
    container_name: prescripciones-service
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://usuario:contrasena@db:5432/cesfam
    ports:
      - "3002:3002"

  pacientes-service:
    build:
      context: ./pacientes-service
    container_name: pacientes-service
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://usuario:contrasena@db:5432/cesfam
    ports:
      - "3003:3003"

  reservas-service:
    build:
      context: ./reservas-service
    container_name: reservas-service
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://usuario:contrasena@db:5432/cesfam
    ports:
      - "3004:3004"

  medicamentos-service:
    build:
      context: ./medicamentos-service
    container_name: medicamentos-service
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://usuario:contrasena@db:5432/cesfam
    ports:
      - "3005:3005"

  entrega-service:
    build:
      context: ./entrega-service
    container_name: entrega-service
    restart: always
    depends_on:
      - db
      - medicamentos-service
    environment:
      DATABASE_URL: postgresql+asyncpg://usuario:contrasena@db:5432/cesfam
      MEDICAMENTOS_BASE_URL: http://medicamentos-service:3005
    ports:
      - "3006:8000"
